fail_fast: true

repos:
  - repo: local
    hooks:
      - id: compute-blog-stats
        name: Compute blog stats
        description: "Computes summary statistics across blog posts and tags."
        entry: bash -c "uv run tools/compute_stats.py && git add -u"
        language: system
        files: '^pages/02\.blog/.*item.*$|^pages/02\.blog/.*frontmatter.*$'
        stages: [pre-commit]
        pass_filenames: false

      - id: render-thumbnails
        name: Render thumbnails
        description: "Renders the thumbnails for all tag pages and for the main blog page."
        entry: bash -c "uv run tools/render_thumbnails.py && git add -u"
        language: system
        files: '^pages/02\.blog/.*item.*$|^pages/02\.blog/.*frontmatter.*$'
        stages: [pre-commit]
        pass_filenames: false

      - id: update-main-stats
        name: Update main blog stats
        description: "Updates the stats shown in the main blog page and in the main tags page."
        entry: bash -c "uv run tools/update_main_stats.py && git add -u"
        language: system
        files: '^pages/02\.blog/.*item.*$|^pages/02\.blog/.*frontmatter.*$'
        stages: [pre-commit]
        pass_filenames: false
