repos:
  - repo: local
    hooks:
      - id: update-blog-stats
        name: Update blog stats
        entry: bash -c 'cog -r pages/02.blog/blog.md && git add pages/02.blog/blog.md'
        language: system
        files: '^pages/02.blog/.*\.md$'
        always_run: true
        stages: [pre-commit]
